version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - master_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    expose:
      - 5432

volumes:
  master_data:
